apiVersion: v1
entries:
  elasticsearch:
  - apiVersion: v1
    appVersion: 6.4.2
    created: "2021-01-25T23:59:43.750317+01:00"
    description: A Helm chart for Elasticsearch cluster
    digest: 8ce0949b19195186220905d003abae81eeca2b00071990a9bd6ce8871d14b3d5
    maintainers:
    - email: alen.komljen@live.com
      name: komljen
      url: https://akomljen.com
    name: elasticsearch
    sources:
    - https://github.com/upmc-enterprises/elasticsearch-operator
    urls:
    - elasticsearch-0.1.6.tgz
    version: 0.1.6
  elasticsearch-curator:
  - apiVersion: v1
    appVersion: 5.5.4
    created: "2021-01-25T23:59:43.750815+01:00"
    description: A Helm chart for Elasticsearch Curator
    digest: 0c26b1d65d5827ec439b76e326ea3deaa69da95d8bc69187c9dd564f117a042b
    home: https://github.com/elastic/curator
    keywords:
    - curator
    - elasticsearch
    - elasticsearch-curator
    maintainers:
    - email: mestdagh.tom@gmail.com
      name: tmestdagh
    - email: gianrubio@gmail.com
      name: gianrubio
    name: elasticsearch-curator
    sources:
    - https://github.com/kubernetes/charts/elasticsearch-curator
    - https://github.com/pires/docker-elasticsearch-curator
    urls:
    - elasticsearch-curator-1.0.1.tgz
    version: 1.0.1
  filebeat:
  - apiVersion: v1
    appVersion: 6.7.0
    created: "2021-01-25T23:59:43.751484+01:00"
    description: A Helm chart to collect Kubernetes logs with filebeat
    digest: 5cf6417768bd7306b1065906b35a8319e399c91bf7ce360d76433c02a90ad357
    home: https://www.elastic.co/products/beats/filebeat
    icon: https://www.elastic.co/assets/blt47799dcdcf08438d/logo-elastic-beats-lt.svg
    maintainers:
    - email: pete.brown@powerhrg.com
      name: rendhalver
    - email: shane.starcher@gmail.com
      name: sstarcher
    name: filebeat
    sources:
    - https://www.elastic.co/guide/en/beats/filebeat/current/index.html
    urls:
    - filebeat-1.7.0.tgz
    version: 1.7.0
  fluent-bit:
  - apiVersion: v1
    appVersion: 1.0.1
    created: "2021-01-25T23:59:43.752278+01:00"
    description: Fast and Lightweight Log/Data Forwarder for Linux, BSD and OSX
    digest: c89c0c22a444fc104d08b8ea1f216b67e8ff8c47ea29a4c80f38ecfea5224b06
    home: http://fluentbit.io
    icon: http://fluentbit.io/assets/img/logo1-default.png
    keywords:
    - logging
    - monitoring
    - fluent
    - fluentd
    maintainers:
    - email: Kevin.Fox@pnnl.gov
      name: kfox1111
    - email: eduardo@treasure-data.com
      name: edsiper
    name: fluent-bit
    sources:
    - http://fluentbit.io
    urls:
    - fluent-bit-1.3.0.tgz
    version: 1.3.0
  kibana:
  - apiVersion: v1
    appVersion: 6.6.1
    created: "2021-01-25T23:59:43.753254+01:00"
    description: Kibana is an open source data visualization plugin for Elasticsearch
    digest: 81c726242e4d30b32d3cec47b3116065636a6e443439701748dbb2ba9699712e
    home: https://www.elastic.co/products/kibana
    icon: https://raw.githubusercontent.com/elastic/kibana/master/src/ui/public/icons/kibana-color.svg
    keywords:
    - elasticsearch
    - kibana
    maintainers:
    - email: casey@monax.io
      name: compleatang
    - email: monotek23@gmail.com
      name: monotek
    name: kibana
    sources:
    - https://github.com/elastic/kibana
    urls:
    - kibana-2.0.0.tgz
    version: 2.0.0
  metricbeat:
  - apiVersion: v1
    appVersion: 6.7.0
    created: "2021-01-25T23:59:43.754074+01:00"
    description: A Helm chart to collect Kubernetes logs with metricbeat
    digest: ede6fa84636b4947e31c1f70ddc91594ee51eace76c85c867d3abc4f9b0db7be
    home: https://www.elastic.co/products/beats/metricbeat
    icon: https://www.elastic.co/assets/blt47799dcdcf08438d/logo-elastic-beats-lt.svg
    maintainers:
    - email: atushi.k@gmail.com
      name: at-k
    - email: ykuoka@gmail.com
      name: mumoshu
    name: metricbeat
    sources:
    - https://www.elastic.co/guide/en/beats/metricbeat/current/index.html
    urls:
    - metricbeat-1.7.0.tgz
    version: 1.7.0
generated: "2021-01-25T23:59:43.749791+01:00"
